project:
  type: book

book:
  title: "WS 25/26 Spanish A1 notes"
  author: "Norah Jones"
  date: "10/10/2025"
  chapters:
    - index.qmd
    - intro.qmd

# bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



